import "./globals.css";
import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { QueryProvider, SsgoiProvider } from "./_providers";

const pretendard = localFont({
  src: [
    {
      path: "../../public/fonts/PretendardVariable.woff2",
      weight: "100 900",
      style: "normal",
    },
  ],
  variable: "--font-pretendard",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className="overflow-x-hidden">
      <body className={`overflow-x-hidden ${pretendard.variable}`}>
        <QueryProvider>
          <SsgoiProvider>{children}</SsgoiProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
