import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { QueryProvider } from "./_providers";

const pretendard = localFont({
  src: [
    {
      path: "../../public/fonts/PretendardVariable.woff2",
      weight: "100 900",
      style: "normal",
    },
  ],
  variable: "--font-pretendard",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${pretendard.variable} `}>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
