import "./globals.css";
import type { Metadata, Viewport } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import { NativeProvider, QueryProvider, SsgoiProvider, UserStateProvider } from "./_providers";

const pretendard = localFont({
  src: [
    {
      path: "../../public/fonts/PretendardVariable.woff2",
      weight: "100 900",
      style: "normal",
    },
  ],
  variable: "--font-pretendard",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  viewportFit: "cover",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="ko" className="overflow-x-hidden">
      <body className={`${pretendard.variable}`} suppressHydrationWarning>
        <SessionProvider session={session}>
          <UserStateProvider>
            <QueryProvider>
              <SsgoiProvider>
                <NativeProvider>{children}</NativeProvider>
              </SsgoiProvider>
            </QueryProvider>
          </UserStateProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
